const brgyPitogo = [
  "Amontay",
  "Biga",
  "Bilucao",
  "Cabulihan",
  "Castillo (Poblacion)",
  "Cawayanin",
  "Cometa",
  "Dalampasigan (Poblacion),",
  "Dulong Bayan (Poblacion)",
  "Gangahin,",
  "Ibabang Burgos",
  "Ibabang Pacatin",
  "Ibabang Piña",
  "Ibabang Soliyao",
  "Ilayang Burgos",
  "Ilayang Pacatin",
  "Ilayang Piña",
  "Ilayang Soliyao,",
  "Maaliw (Poblacion)",
  "Manggahan (Poblacion)",
  "Masaya (Poblacion)",
  "Mayubok (Poblacion)",
  "Nag‑Cruz",
  "Osmeña",
  "Pag‑asa (Poblacion),",
  "Pamilihan (Poblacion)",
  "Payte",
  "Pinagbayanan",
  "Poctol",
  "Quezon",
  "Quinagasan",
  "Rizalino",
  "Saguinsinan",
  "Sampaloc",
  "San Roque",
  "Sisirin",
  "Sumag Este",
  "Sumag Norte",
  "Sumag Weste"
];

module.exports = brgyPitogo;