const brgyInfanta = [
  "Abiawin",
  "Agos‑agos",
  "Alitas",
  "Amolongin",
  "Anibong",
  "Antikin",
  "Bacong",
  "Balobo",
  "Bantilan",
  "Banugao",
  "Batican",
  "Binonoan",
  "Binulasan",
  "Boboin",
  "Catambungan",
  "Cawaynin",
  "Comon",
  "Dinahican",
  "Gumian",
  "Ilog",
  "Ingas",
  "Langgas",
  "Libjo",
  "Lual",
  "Magsaysay",
  "Maypulot",
  "Miswa",
  "Pilaway",
  "Pinaglapatan,",
  "Poblacion 1 (Barangay 1)",
  "Poblacion 38 (Poblacion Barangay 2)",
  "Poblacion 39 (Poblacion Barangay 3)",
  "Pulo",
  "Silangan",
  "Tongohin",
  "Tudturan"
];

module.exports = brgyInfanta;