const brgyUnisan = [
  "Almacen",
  "Balagtas",
  "Balanacan",
  "Bonifacio",
  "Bulo Ibaba",
  "Bulo Ilaya",
  "Burgos",
  "Cabulihan Ibaba",
  "Cabulihan Ilaya",
  "Caigdal",
  "F. de Jesus (Poblacion)",
  "General Luna",
  "Kalilayan Ibaba",
  "Kalilayan Ilaya",
  "Mabini",
  "Mairok Ibaba",
  "Mairok Ilaya",
  "Malvar",
  "Maputat",
  "Muliguin",
  "Pagaguasan",
  "Panaon Ibaba",
  "Panaon Ilaya",
  "Plaridel",
  "Poctol",
  "Punta",
  "R. Lapu‑lapu (Poblacion)",
  "R. Magsaysay (Poblacion)",
  "Raja Soliman (Poblacion)",
  "Rizal Ibaba",
  "Rizal Ilaya",
  "San Roque",
  "Socorro",
  "Tagumpay",
  "Tubas",
  "Tubigan"
];

module.exports = brgyUnisan;