const brgyMauban = [
  "Abo‑abo",
  "Alitap",
  "Baao",
  "Bagong Bayan (Poblacion)",
  "Balaybalay",
  "Bato",
  "Cagbalete I",
  "Cagbalete II",
  "Cagsiay I",
  "Cagsiay II",
  "Cagsiay III",
  "Concepcion",
  "Daungan (Poblacion)",
  "Liwayway",
  "Lual (Poblacion)",
  "Lual Rural",
  "Lucutan",
  "Luya‑luya",
  "Mabato (Poblacion)",
  "Macasin",
  "Polo",
  "Remedios I",
  "Remedios II",
  "Rizaliana (Poblacion)",
  "Rosario",
  "Sadsaran (Poblacion)",
  "San Gabriel",
  "San Isidro",
  "San Jose",
  "San Lorenzo",
  "San Miguel",
  "San Rafael",
  "San Roque",
  "San Vicente",
  "Santa Lucia",
  "Santo Angel",
  "Santo Niño",
  "Santol",
  "Soledad",
  "Tapucan"
]

module.exports = brgyMauban;