const brgyCatanauan = [
  "Ajos",
  "Anusan",
  "Barangay 1 (Poblacion)",
  "Barangay 10 (Poblacion)",
  "Barangay 2 (Poblacion)",
  "Barangay 3 (Poblacion)",
  "Barangay 4 (Poblacion)",
  "Barangay 5 (Poblacion)",
  "Barangay 6 (Poblacion)",
  "Barangay 7 (Poblacion)",
  "Barangay 8 (Poblacion)",
  "Barangay 9 (Poblacion)",
  "Bolo",
  "Bulagsong",
  "Camandiison",
  "Canculajao",
  "Catumbo",
  "Cawayanin Ibaba",
  "Cawayanin Ilaya",
  "Cutcutan",
  "Dahican",
  "Doongan Ibaba",
  "Doongan Ilaya",
  "Gatasan",
  "Macpac",
  "Madulao",
  "Matandang Sabang Kanluran",
  "Matandang Sabang Silangan",
  "Milagrosa",
  "Navitas",
  "Pacabit",
  "San Antonio Magkupa",
  "San Antonio Pala",
  "San Isidro",
  "San Jose (Anyao)",
  "San Pablo (Suha)",
  "San Roque (Doyon)",
  "San Vicente Kanluran",
  "San Vicente Silangan",
  "Santa Maria (Dao)",
  "Tagabas Ibaba",
  "Tagabas Ilaya",
  "Tagbacan Ibaba,",
  "Tagbacan Ilaya",
  "Tagbacan Silangan",
  "Tuhian"
];

module.exports = brgyCatanauan;