const brgyTiaong = [
  "Anastacia (Tagbak)",
  "Aquino",
  "Ayusan I",
  "Ayusan II",
  "Barangay I (Poblacion)",
  "Barangay II (Poblacion)",
  "Barangay III (Poblacion)",
  "Barangay IV (Poblacion)",
  "Behia",
  "Bukal",
  "Bula",
  "Bulakin",
  "Cabatang",
  "Cabay",
  "Del Rosario",
  "Lagalag",
  "Lalig",
  "Lumingon",
  "Lusacan",
  "Paiisa",
  "Palagaran",
  "Quipot",
  "San Agustin",
  "San Francisco",
  "San Isidro",
  "San Jose",
  "San Juan",
  "San Pedro",
  "Tagbakin",
  "Talisay",
  "Tamisian"
];

module.exports = brgyTiaong;