const brgySariaya = [
  "Antipolo",
  "Balubal",
  "Barangay 1 (Poblacion)",
  "Barangay 2 (Poblacion)",
  "Barangay 3 (Poblacion)",
  "Barangay 4 (Poblacion)",
  "Barangay 5 (Poblacion)",
  "Barangay 6 (Poblacion)",
  "Bignay 1",
  "Bignay 2",
  "Bucal",
  "Canda",
  "Castañas",
  "Concepcion Banahaw",
  "Concepcion No. 1",
  "Concepcion Palasan",
  "Concepcion Pinagbakuran",
  "Gibanga",
  "Guisguis‑San Roque",
  "Guisguis‑Talon",
  "Janagdong 1",
  "Janagdong 2",
  "Limbon",
  "Lutucan 1",
  "Lutucan Bata",
  "Lutucan Malabag",
  "Mamala I",
  "Mamala II",
  "Manggalang 1",
  "Manggalang Tulo‑tulo",
  "Manggalang‑Bantilan",
  "Manggalang‑Kiling",
  "Montecillo,",
  "Morong",
  "Pili",
  "Sampaloc 1",
  "Sampaloc 2",
  "Sampaloc Bogon",
  "Sampaloc Santo Cristo",
  "Talaan Aplaya",
  "Talaanpantoc",
  "Tumbaga 1",
  "Tumbaga 2"
];

module.exports = brgySariaya;