const brgyTagkawayan = [
  "Aldavoc",
  "Aliji",
  "Bagong Silang",
  "Bamban",
  "Bosigon",
  "Bukal",
  "Cabibihan",
  "Cabugwang",
  "Cagascas",
  "Candalapdap",
  "Casispalan",
  "Colong‑colong",
  "Del Rosario",
  "Katimo",
  "Kinatakutan",
  "Landing",
  "Laurel",
  "Magsaysay",
  "Maguibuay",
  "Mahinta",
  "Malbog",
  "Manato Central",
  "Manato Station",
  "Mangayao",
  "Mansilay",
  "Mapulot",
  "Munting Parang",
  "Payapa",
  "Poblacion",
  "Rizal",
  "Sabang ",
  "San Diego",
  "San Francisco",
  "San Isidro",
  "San Roque",
  "San Vicente",
  "Santa Cecilia",
  "Santa Monica",
  "Santo Niño I",
  "Santo Niño II",
  "Santo Tomas",
  "Seguiwan",
  "Tabason",
  "Tunton",
  "Victoria"
];

module.exports = brgyTagkawayan;