const brgyTayabas = [
  "Alitao",
  "Alsam Ibaba",
  "Alsam Ilaya",
  "Alupay",
  "Angeles Zone I (Poblacion)",
  "Angeles Zone II",
  "Angeles Zone III",
  "Angeles Zone IV",
  "Angustias Zone I (Poblacion)",
  "Angustias Zone II",
  "Angustias Zone III",
  "Angustias Zone IV",
  "Anos",
  "Ayaas",
  "Baguio",
  "Banilad",
  "Bukal Ibaba",
  "Bukal Ilaya",
  "Calantas",
  "Calumpang",
  "Camaysa",
  "Dapdap",
  "Domoit Kanluran",
  "Domoit Silangan",
  "Gibanga",
  "Ibas",
  "Ilasan Ibaba",
  "Ilasan Ilaya",
  "Ipilan",
  "Isabang",
  "Katigan Kanluran",
  "Katigan Silangan",
  "Lakawan",
  "Lalo",
  "Lawigue",
  "Lita (Poblacion)",
  "Malaoa",
  "Masin",
  "Mate",
  "Mateuna",
  "Mayowe",
  "Nangka Ibaba",
  "Nangka Ilaya",
  "Opias",
  "Palale Ibaba",
  "Palale Ilaya",
  "Palale Kanluran",
  "Palale Silangan",
  "Pandakaki",
  "Pook",
  "Potol",
  "San Diego Zone I (Poblacion)",
  "San Diego Zone II",
  "San Diego Zone III",
  "San Diego Zone IV",
  "San Isidro Zone I (Poblacion)",
  "San Isidro Zone II",
  "San Isidro Zone III",
  "San Isidro Zone IV",
  "San Roque Zone I (Poblacion)",
  "San Roque Zone II",
  "Talolong",
  "Tamlong",
  "Tongko",
  "Valencia",
  "Wakas"
];

module.exports = brgyTayabas;