const brgyLucban = [
  "Abang",
  "Aliliw",
  "Atulinao",
  "Ayuti",
  "Barangay 1 (Poblacion)",
  "Barangay 2 (Poblacion)",
  "Barangay 3 (Poblacion)",
  "Barangay 4 (Poblacion)",
  "Barangay 5 (Poblacion)",
  "Barangay 6 (Poblacion)",
  "Barangay 7 (Poblacion)",
  "Barangay 8 (Poblacion)",
  "Barangay 9 (Poblacion)",
  "Barangay 10 (Poblacion)",
  "Igang",
  "Kabatete",
  "Kakawit",
  "Kalangay",
  "Kalyaat",
  "Kilib",
  "Kulapi",
  "Mahabang Parang",
  "Malupak",
  "Manasa",
  "May‑It",
  "Nagsinamo",
  "Nalunao",
  "Palola",
  "Piis",
  "Samil",
  "Tiawe",
  "Tinamnan"
];

module.exports = brgyLucban;