const brgyCalauag = [
  "Agoho",
  "Anahawan",
  "Anas",
  "Apad Lutao",
  "Apad Quezon",
  "Apad Taisan",
  "Atulayan",
  "Baclaran",
  "Bagong Silang",
  "Balibago",
  "Bangkuruhan",
  "Bantolinao",
  "Barangay I (Poblacion)",
  "Barangay II (Poblacion)",
  "Barangay III (Poblacion)",
  "Barangay IV (Poblacion)",
  "Barangay V (Poblacion)",
  "Bigaan",
  "Binutas",
  "Biyan",
  "Bukal",
  "Buli",
  "Dapdap",
  "Dominlog",
  "Doña Aurora",
  "Guinosayan",
  "Ipil",
  "Kalibo (Santa Cruz)",
  "Kapaluhan",
  "Katangtang",
  "Kigtan",
  "Kinalin Ibaba",
  "Kinalin Ilaya",
  "Kinamaligan",
  "Kumaludkud",
  "Kunalum",
  "Kuyaoyao",
  "Lagay",
  "Lainglaingan",
  "Lungib",
  "Mabini",
  "Madlangdungan",
  "Maglipad (Rosario)",
  "Maligaya",
  "Mambaling",
  "Manhulugin",
  "Marilag (Punaya)",
  "Mulay",
  "Pandanan",
  "Pansol",
  "Patihan",
  "Pinagbayanan",
  "Pinagkamaligan",
  "Pinagsakahan",
  "Pinagtalleran",
  "Rizal Ibaba",
  "Rizal Ilaya",
  "Sabang I",
  "Sabang II",
  "Salvacion",
  "San Quintin",
  "San Roque Ibaba",
  "San Roque Ilaya",
  "Santa Cecilia",
  "Santa Maria",
  "Santa Milagrosa",
  "Santa Rosa",
  "Santo Angel (Pangahoy)",
  "Santo Domingo",
  "Sinag",
  "Sumilang",
  "Sumulong",
  "Tabansak",
  "Talingting",
  "Tamis",
  "Tikiwan",
  "Tiniguiban",
  "Villa Magsino",
  "Villa San Isidro",
  "Viñas",
  "Yaganak"
];

module.exports = brgyCalauag;