const brgyAtimonan = [
  "Angeles",
  "Balubad",
  "Balugohin",
  "Barangay Zone 1 (Poblacion)",
  "Barangay Zone 2 (Poblacion)",
  "Barangay Zone 3 (Poblacion)",
  "Barangay Zone 4 (Poblacion)",
  "Buhangin",
  "Caridad Ibaba",
  "Caridad Ilaya",
  "Habingan",
  "Inaclagan",
  "Inalig",
  "Kilait",
  "Kulawit",
  "Lakip",
  "Lubi",
  "Lumutan",
  "Magsaysay",
  "Malinao Ibaba",
  "Malinao Ilaya",
  "Malusak",
  "Manggalayan Bundok",
  "Manggalayan Labak",
  "Matanag",
  "Montes Balaon",
  "Montes Kallagan",
  "Ponon",
  "Rizal",
  "San Andres Bundok",
  "San Andres Labak",
  "San Isidro",
  "San Jose Balatok",
  "San Rafael",
  "Santa Catalina",
  "Sapaan",
  "Sokol",
  "Tagbakin",
  "Talaba",
  "Tinandog",
  "Villa Ibaba",
  "Villa Ilaya"
];

module.exports = brgyAtimonan