const Lopez = [
  "Bacungan",
  "Bagacay",
  "Banabahin Ibaba",
  "Banabahin Ilaya",
  "Bayabas",
  "Bebito",
  "Bigajo",
  "Binahian A",
  "Binahian B",
  "Binahian C",
  "Bocboc",
  "Buenavista",
  "Burgos (Poblacion)",
  "Buyacanin",
  "Cagacag",
  "Calantipayan",
  "Canda Ibaba",
  "Canda Ilaya",
  "Cawayan",
  "Cawayanin",
  "Cogorin Ibaba,",
  "Cogorin Ilaya",
  "Concepcion",
  "Danlagan",
  "De La Paz",
  "Del Pilar",
  "Del Rosario",
  "Esperanza Ibaba",
  "Esperanza Ilaya",
  "Gomez (Poblacion)",
  "Guihay",
  "Guihay",
  "Guites",
  "Hondagua",
  "Ilayang Ilog A",
  "Ilayang Ilog B",
  "Inalusan",
  "Jongo",
  "Lalaguna",
  "Lourdes",
  "Mabanban",
  "Mabini",
  "Magallanes",
  "Magsaysay (Poblacion)",
  "Maguilayan",
  "Mahayod‑Hayod",
  "Mal‑ay",
  "Mandoog",
  "Manguisian",
  "Matinik",
  "Monteclaro",
  "Pamampangin",
  "Pansol",
  "Peñafrancia",
  "Pisipis",
  "Rizal (Rural)",
  "Rizal (Poblacion)",
  "Roma",
  "Rosario",
  "Samat",
  "San Andres",
  "San Antonio",
  "San Francisco A",
  "San Francisco B",
  "San Isidro",
  "San Jose",
  "San Miguel (Dao",
  "San Pedro",
  "San Rafael",
  "San Roque",
  "Santa Catalina",
  "Santa Elena",
  "Santa Jacobe",
  "Santa Lucia",
  "Santa Maria",
  "Santa Rosa",
  "Santa Teresa (Mayupag)",
  "Santo Niño Ibaba",
  "Santo Niño Ilaya",
  "Silang",
  "Sugod",
  "Sumalang",
  "Talolong (Poblacion)",
  "Tan‑ag Ibaba",
  "Tan‑ag Ilaya",
  "Tocalin",
  "Vegaflor",
  "Vergaña",
  "Veronica",
  "Villa Aurora",
  "Villa Espina",
  "Villa Geda",
  "Villa Hermosa",
  "Villamonte",
  "Villanacaob"
];

module.exports = Lopez;