const brgyLucena = [
  "Barangay 1 (Poblacion)",
  "Barangay 2 (Poblacion)",
  "Barangay 3 (Poblacion)",
  "Barangay 4 (Poblacion)",
  "Barangay 5 (Poblacion)",
  "Barangay 6 (Poblacion)",
  "Barangay 7 (Poblacion)",
  "Barangay 8 (Poblacion)",
  "Barangay 9 (Poblacion)",
  "Barangay 10 (Poblacion)",
  "Barangay 11 (Poblacion)",
  "Barra",
  "Bocohan",
  "Cotta",
  "Gulang-Gulang",
  "Dalahican",
  "Domoit",
  "Ibabang Dupay",
  "Ibabang Iyam",
  "Ibabang Talim",
  "Ilayang Dupay",
  "Ilayang Iyam",
  "Ilayang Talim",
  "Isabang",
  "Market View",
  "Mayao Castillo",
  "Mayao Crossing",
  "Mayao Kanluran",
  "Mayao Parada",
  "Mayao Silangan",
  "Ransohan",
  "Salinas",
  "Talao-Talao"
];

module.exports = brgyLucena;