const brgyGumaca = [
  "Adia Bitaog",
  "Anonangin",
  "Bagong Buhay (Poblacion)",
  "Bamban",
  "Bantad",
  "Batong Dalig",
  "Biga",
  "Binambang",
  "Buensuceso",
  "Bungahan",
  "Butaguin",
  "Calumangin",
  "Camohaguin",
  "Casasahan Ibaba",
  "Cawayan",
  "Gayagayaan",
  "Gitnang Barrio",
  "Hagakhakin",
  "Hardinan",
  "Inaclagan",
  "Inagbuhan Ilaya",
  "Labnig",
  "Laguna",
  "Lagyo",
  "Mabini (Poblacion)",
  "Mabunga",
  "Malabtog",
  "Manlayaan",
  "Marcelo H. del Pilar",
  "Mataas na Bundok",
  "Maunlad (Poblacion)",
  "Pagsabangan",
  "Panikihan",
  "Peñafrancia (Poblacion)",
  "Pipisik (Poblacion)",
  "Progreso",
  "Rizal (Poblacion)",
  "Rosario",
  "San Agustin",
  "San Diego",
  "San Diego Poblacion",
  "San Isidro Kanluran",
  "San Isidro Silangan",
  "San Juan de Jesus",
  "San Vicente",
  "Sastre",
  "Tabing Dagat (Poblacion)",
  "Tumayan",
  "Villa Arcaya",
  "Villa Bota",
  "Villa Fuerte",
  "Villa M. Principe",
  "Villa Mendoza",
  "Villa Nava",
  "Villa Padua",
  "Villa Perez",
  "Villa Tañada",
  "Villa Victoria"
];

module.exports = brgyGumaca