const brgyMacalelon = [
  "Amontay",
  "Anos",
  "Buyao",
  "Calantas",
  "Candangal",
  "Castillo (Poblacion)",
  "Damayan (Poblacion)",
  "Lahing",
  "Luctob",
  "Mabini Ibaba",
  "Mabini Ilaya",
  "Malabahay",
  "Mambog",
  "Masipag (Poblacion)",
  "Olongtao Ibaba",
  "Olongtao Ilaya",
  "Padre Herrera",
  "Pag‑asa (Poblacion)",
  "Pajarillo",
  "Pinagbayanan",
  "Rizal (Poblacion)",
  "Rodriquez (Poblacion)",
  "San Isidro",
  "San Jose",
  "San Nicolas",
  "San Vicente",
  "Taguin",
  "Tubigan Ibaba",
  "Tubigan Ilaya",
  "Vista Hermosa"
];

module.exports = brgyMacalelon