const brgyBuenavista = [
  "Bagong Silang",
  "Batabat Norte",
  "Batabat Sur",
  "Buenavista",
  "Bukal",
  "Bulo",
  "Cabong",
  "Cadlit",
  "Catulin",
  "Cawa",
  "De La Paz",
  "Del Rosario",
  "Hagonghong",
  "Ibabang Wasay",
  "Ilayang Wasay",
  "Lilukin",
  "Mabini",
  "Mabutag",
  "Magallanes",
  "Maligaya (Esperanza)",
  "Manlana",
  "Masaya",
  "Poblacion",
  "Rizal",
  "Sabang Pinamasagan",
  "Sabang Piris",
  "San Diego",
  "San Isidro Ibaba",
  "San Isidro Ilaya",
  "San Pablo",
  "San Pedro (Villa Rodrigo)",
  "San Vicente",
  "Siain",
  "Villa Aurora",
  "Villa Batabat",
  "Villa Magsaysay",
  "Villa Veronica"
];

module.exports = brgyBuenavista;